Fix rms/crncc 2256
PA-NIHR-CRN/dte-study-api pull request #118
Opened 2024-09-02 09:32 UTC by Tkirkwood

removed progress indicator, 'question x of y'
changed progress bar to only show when there are 3 or more pages.

2024-09-02 09:41 UTC, kevinofficer approved these changes

2024-09-02 09:55 UTC, con-nihr reviewed
The original requirements don't seem to be GDS compliant.

Hold off until we have clarification.

We might just remove the progress bar and question indicator text completely.

2024-09-02 09:56 UTC, con-nihr requested changes
On hold pending clarification.

2024-09-03 14:27 UTC, con-nihr commented on BPOR/BPOR.Rms/Views/Researcher/SubmitStudy.cshtml
> -                var step = ViewData["Step"] as int?;
Check where else we are using `ViewData["Step"]` and `ViewData["TotalSteps"]` if it is not read _anywhere_ anymore, remove all the locations that are setting this these values.

e.g.
https://github.com/PA-NIHR-CRN/dte-study-api/pull/115/files#diff-a27974a40fdd743b11a3a7b0675ac1d489fdd14c19f875f6c8487e7c0362c0c6R174

2024-09-03 16:20 UTC, con-nihr approved these changes

2024-09-03 16:21 UTC, merged